---
name: "pipeline-components-perl-critic"
description: "perlcritic by Pipeline Components"
author: "Robbert Müller <spam.me@grols.ch>"
branding:
  icon: "flag"
  color: "green"
inputs:
  directory:
    description: "Directory to lint"
    required: false
    default: .
  options:
    description: "Additional options"
    required: false
    default: ""
runs:
  using: "docker"
  image: docker://pipelinecomponents/perl-critic
  args:
    - perlcritic
    - "${{ inputs.options }}"
    - "${{ inputs.directory }}"
